### ISSUE TITLE
Intermediate VCF, BD clarification

### ISSUE THREAD

**Issue by Lenbok** [ga4gh/benchmarking-tools#2]
For the decision (BD) field, it is fairly obvious what TP/FP/FN mean, but it could be good to clarify the meaning of 'N' (and what the intended use is). 

Am I right in assuming a 'N' is used to indicate that the call was not assessed / skipped / other? And I assume where there is no call (i.e. empty GT), the field should just have a regular VCF missing value '.'. 

In vcfeval, calls may have non TP/FP/FN status either because they were ignored from comparison (e.g. outside of BED region; non-variant GT; SV or symbolic; having non-pass FILTER; exceeding maximum length; off-reference), or if the variant could not be assessed due to being in a region that turned out to exceed maximum evaluation complexity -- I assume these would need to end up with BD as 'N' or perhaps missing.

**Comment by pkrusche** [comment]
Yes, this was the intention with "N" : flag calls that were not compared / could not be assigned a truth status. The BT field (#3) could give additional information on what happened.
