### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by ghost** [ga4gh/benchmarking-tools#23]
Hi Justin,

The link
https://github.com/ga4gh/benchmarking-tools/blob/master/doc/ref-impl/doc/resources/stratification-bed-files

in https://github.com/ga4gh/benchmarking-tools/blob/master/doc/ref-impl/stratification.md currently goes to a 404.

Thanks!
-Kaushik

**Comment by andrewjesaitis** [comment]
Merged in #24
