### ISSUE TITLE
Intermediate VCF, what is BT field for?

### ISSUE THREAD

**Issue by Lenbok** [ga4gh/benchmarking-tools#3]
Currently the BT description is "Type of comparison performed" and it is in the ROC section. I'm not sure what the intended contents of this field are, so some examples would help. Is it just a textual name for where the QQ value was derived perhaps for graph labelling? (e.g. "QUAL", "My Favourite Callset Name")

**Comment by pkrusche** [comment]
In hap.py/xcmp I would use this field to show where haplotype vs. direct matching was performed, or to indicate errors. The exact meaning of the field would probably be up to the comparison engine creator, which is why I made it optional.
