### ISSUE TITLE
Intermediate VCF, SUPERLOCUS_ID

### ISSUE THREAD

**Issue by Lenbok** [ga4gh/benchmarking-tools#5]
There is a potential complication with respect to the SUPERLOCUS_ID, (at least as it applies to vcfeval). The boundaries of vcfeval sync regions are dependent on the variant positions after some internal trimming (e.g. removal of VCF anchor base where applicable, and the "relaxed-reference" mode potentially trims many leading same-as-reference bases).

What this means is that for a side-by-side output VCF record that preserves the input variant representation, occasionally the TRUTH may be in one sync region, and the QUERY may be in another. 

In the combined output of dev vcfeval these cases are handled by setting the equivalent field to just contain two ids (comma separated), which is not really easy to deal with if you plan on doing downstream superlocus-oriented statistics. Reasonable alternatives would be to move SUPERLOCUS_ID to FORMAT (seems a bit ugly since it's fairly rare), or when such cases arise just veto the merge and output two separate records (probably a good compromise).

**Comment by pkrusche** [comment]
I agree that just writing two lines would probably be the easiest solution for this corner case.

**Comment by Lenbok** [comment]
One other minor thing - the annotations that we declare have terse IDs, so to keep a consistent style, perhaps this should be something like SID (superlocus ID), BS (benchmarking superlocus), etc. (The difference is visually apparent once you start eyeballing the resulting VCFs)

**Comment by pkrusche** [comment]
+1 -- let's change that once #7 is resolved.

**Comment by Lenbok** [comment]
Now we are sticking with the superlocus term, do you have any preference or alternative tag for this @pkrusche ? I would probably go for BS myself but it's not a strong preference.

**Comment by jzook** [comment]
I'm happy with either SID or BS, and agree shortening the name is a good
idea.  Since most other tags are 2 characters, I have a slight preference
for BS as well

**Comment by pkrusche** [comment]
I proposed some changes to the intermediate format definitions, do these look OK to you?

**Comment by Lenbok** [comment]
They look fine to me.
