### ISSUE TITLE
Can we call a "superlocus" a "window"?

### ISSUE THREAD

**Issue by ghost** [ga4gh/benchmarking-tools#7]
From how a "superlocus" was defined to me during the NY meeting, I think the traditional term "window" may be more appropriate. The term "window" is a very standard term for any one doing serial processing and, to me, is more to the point than superlocus. Thanks!

**Comment by Lenbok** [comment]
I have no prior attachments to the term superlocus (in vcfeval we have always talked about "synchronization points", from which you could later choose to separate the reference into regions), but I think that superlocus is nicely vague about how one determines the regions etc. As a programmer, the term "window" carries a bit much implementation baggage for me, none of which fits with the vcfeval dynamic programming algorithm.

**Comment by jzook** [comment]
My inclination is to stick with "superlocus" as well since it has a particular meaning in benchmarking variants that I think is different from the traditional definition of window.  I don't have a strong opinion about this though as long as we define whatever term we use.

**Comment by pkrusche** [comment]
I am in favour of keeping superlocus also. We could define the superlocus variants as a set of variants that intends to fully describe the variation within a contiguous reference region. This should be general enough to cover @bioinformed's maximal superloci, hap.py's haplotype blocks and variant sets between sync points in vcfeval?

**Comment by jzook** [comment]
Do you think we could be a bit more specific about the intention and still
include all 3 tools?  Perhaps: "a set of variants that intends to fully
describe the variation within a contiguous reference region that may
contain complex variation with different representations."  It might also
be nice to have examples of more specifically how each of the tools defines
it.

**Comment by Lenbok** [comment]
So, following on from our call yesterday, we are retaining the term superlocus.
